version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: demandes-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demandes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: demandes-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/demandes_db?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy || npx prisma migrate dev --name init && npm run dev"

  frontend:
    build: ./frontend
    container_name: demandes-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
